# Header

menu:
  主页: /
  随笔: /tags/随笔/
  #相册: photo

# SubNav
subnav:
  github: "https://github.com/ProgramDreamer"
  weibo: "http://weibo.com/p/1005055334475241/home?from=page_100505&mod=TAB&is_all=1#place"
  #rss: "/atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=AXZpZHNkL3htdkFwcC9ibmw"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '一分钱也是爱，煎饼果子加个蛋'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: 

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /img/favicon.png

#你的头像url
avatar: /img/img.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
#duoshuo: false

#2、网易云跟帖
wangyiyun: true
 

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#CAFFFF'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  百度: http://www.baidu.com/
  谷歌: http://www.google.com/
  哔哩哔哩: http://www.bilibili.com/
  github: http://www.github.com/
  码云: http://git.oschina.net/
  maven: http://search.maven.org/

aboutme: 年少无为&nbsp;&nbsp;即将毕业&nbsp;&nbsp;前途渺茫<br>的一枚码字工<br><br><br><br><br>你想用卖糖水来度过余生<br>还是想要一个机会来改变世界?<br><br><br><br>点击'邮箱'按钮<br>欢迎您提出宝贵的建议^_^